### ISSUE TITLE
Expiring Pinterest API Token Every 24 Hours

### ISSUE THREAD

**Issue by nvdpsingh** [nvdpsingh23/Project-2#2]
The Pinterest API token expires every 24 hours, causing the user login process to break. A new token needs to be requested and implemented daily to maintain functionality. We need to find a way to refresh the token automatically or use a more persistent authentication mechanism.

**Comment by Jathin21** [comment]
Pinterest's API should provide a way to refresh the token. Here’s how to use it:

    Generate a Long-Lived Access Token
    Visit the Pinterest Developers page to generate an access token:
        Use the /oauth/token endpoint to exchange a refresh token for a new access token.

    Example Request:

POST https://api.pinterest.com/v5/oauth/token
Content-Type: application/x-www-form-urlencoded

client_id=<YOUR_CLIENT_ID>
client_secret=<YOUR_CLIENT_SECRET>
grant_type=refresh_token
refresh_token=<YOUR_REFRESH_TOKEN>
