### ISSUE TITLE
Handling Google Vision API Quotas and Limits

### ISSUE THREAD

**Issue by nvdpsingh** [nvdpsingh23/Project-2#4]
The Google Vision API has strict quota limits, which could impact the application’s ability to process multiple pins in a short period. We need to handle error responses and implement a mechanism to manage quota limits effectively without affecting the user experience.

**Comment by Jathin21** [comment]
To address Google Vision API's strict quota limits, implement robust error handling to identify quota-related issues (e.g., HTTP 429) and provide fallback messages to users. Use batching or a request queue to space out API calls and avoid exceeding limits. Cache results of processed images using tools like Redis or an in-memory store to reduce duplicate requests. Additionally, monitor API usage through Google Cloud Monitoring, setting up alerts for quota thresholds. These strategies ensure smooth application functionality while effectively managing quota constraints.
